= SimpleApp

This is a simple link:http://isis.apache.org[Apache Isis] application, but structured so it can be used as a starting point for developing your own applications.



== Quick start

Build using:

[source,bash]
----
mvn clean install
----

Run using:

[source,bash]
----
mvn -pl webapp spring-boot:run
----

Login using: 

* username: `sven`
* password: `pass`

The app runs with H2 running in-memory, with sample data set up using link:https://isis.apache.org/guides/ugtst.html#_ugtst_fixture-scripts[fixture scripts].



== Application Structure

The following table explains the contents of each of the directories:

[width="100%",options="header,footer",stripes="none",cols="2a,4a"]
|====================
|Directory
|Description

|`module-simple`
|Holds the "simple" module, consisting of the `SimpleObject` entity and supporting services.
It also contains module-specific unit- and integration tests.

[TIP]
====
Larger applications should consist of multiple modules; each such module can be copied from this starter module.
====

|`webapp`
|Holds the bootstrapping classes, along with application-level scoped services and home page.
It also contains application-wide integration tests/BDD specs, and lockdown tests.

The `pom.xml` also provides goals to run the app from the command line, or to be assembled into a Docker image.

|====================


== In Development

Apache Isis uses DataNucleus as its ORM, which requires that any entities are "enhanced", a post-compile process.

Normally this is done as part of a "mvn clean install", but the entities can also be enhanced explicity using:

[source,bash]
----
mvn -pl module-simple datanucleus:enhance -o
----

This is useful to know if the application or integration test fails to bootstrap, complaining of "unenhanced entities".

TIP: You can also use `enhance-all.sh`


== Testing

To disable the running of unit tests: +

[source,bash]
----
mvn -DskipUTs 
----

[TIP]
====
By default, output of unit tests are in  `target/surefire-unittest-reports` (in the ``module-simple`` modules).
====

To disable the running of integration tests: +

[source,bash]
----
mvn -DskipITs 
----

[TIP]
====
By default, output of integration tests are in  `target/surefire-integtest-reports` (in the ``application`` and ``module-simple`` modules).
====

To disable the running of BDD specs: +

[source,bash]
----
mvn -DskipBSs 
----

[TIP]
====
By default, output of integration tests are in  `target/surefire-integbddspecs-reports` (in the ``application`` module).
====

* To disable the running of all tests and BDD specs: +
+
[source,bash]
----
mvn -DskipTests 
----


== Docker

To package up the application as a docker image and push to a Docker registry:

* set `$DOCKER_REGISTRY_USERNAME` and `$DOCKER_REGISTRY_PASSWORD` environment variables

* modify the `to/image` configuration property for the link:https://github.com/GoogleContainerTools/jib[jib-maven-plugin] in the `pom.xml`
+
The default value is `docker.io/apacheisis/simpleapp:latest`:

** change `docker.io` prefix to push to a registry other than Docker hub
** change `apacheisis/simpleapp` to the name of your app.

* package up the app with the `docker` profile:
+
[source,bash]
----
mvn -pl webapp -DskipTests -Ddocker package
----

Variants:

* to specify Docker registry credentials through some other mechanism, configure the `pom.xml` for `maven-jib-plugin` (it supports a link:https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#authentication-methods[variety of ways] to specify credentials)

* to override the image at the command line, use `-Dimage=...`.



To run a docker image previously packaged:

[source,bash]
----
docker pull apacheisis/simpleapp:latest
docker container run -d -p 8080:8080 apacheisis/simpleapp:latest
----

This can then be accessed at link:http://localhost:8080[localhost:8080].


== Externalized Configuration

The application is configured to run in the `/run/secrets` directory.
Configuration can be therefore be externalized by defining an `application.properties` secret for the Kubernetes or Docker Swarm cluster.

Spring Boot will use these settings in preference to the configuration properties defined in `classpath:config/application.properties`, see link:https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config[Spring docs].
